name = "liqueur-solutions-worker"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-01"
workers_dev = true

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = 'MIXTURE_BUCKET'
bucket_name = 'mixture-files'
preview_bucket_name = 'mixture-files-dev'

[observability]
enabled = true
head_sampling_rate = 1
