name = "liqueur-solutions-worker"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-01"
workers_dev = true

[build]
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"
PNPM_VERSION = "9.10.0"

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = 'MIXTURE_BUCKET'
bucket_name = 'mixture-files'
preview_bucket_name = 'mixture-files-dev'

[observability]
enabled = true
head_sampling_rate = 1
